config/routes.rb
Rails.application.routes.draw do
   get 'favorites/new'

  get 'sessions/new'

  get 'welcome/index'
  
    resources :posts do
    resources :comments do
    collection do
      post :confirm
    end
    end
  end
  
  resources :comments, only: [:create, :destroy]

  resources :favorites, only: [:create, :destroy]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

 root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container-fluid" style="margin:2% 0 18% 0">
  <h1 class="text-center">INSTAGRAMCLONE APPLICATION</h1>
  <div class="row" style="margin-top:2%">
    <div class="col-sm-6 text-right">  
      <img src="/instagra.png"  alt="Dominic">
    </div>
    <div class=" text-left">  
      <h1 class=" text-center">Log in</h1>
      <%= form_with(scope: :session, url: sessions_path) do |f| %>
      <ul>
      <div class="row col-sm-12">
        <li class="col-sm-4"><%= f.label :email %></li>
        <li class="col-sm-8"><%= f.email_field :email %></li>
      </div>
      <br>
      <div class="row col-sm-12">
        <li class="col-sm-4"><%= f.label :password %></li>
        <li class="col-sm-8"><%= f.password_field :password %></li>
      </div>
      <br>
      <div class="row col-sm-12 text-center"> 
        <li class="col-sm-12"><%= f.submit "Log in" %></li>
      </div>
      </ul>
      <% end %>
      <h3>Don't you have account? <button type="button" class="btn btn-outline-primary"><%= link_to "Sign up", new_user_path %></button> here!</h5>
      
    </div>
</div>
</div>