config/routes.rb
Rails.application.routes.draw do
   get 'favorites/new'

  get 'sessions/new'

  get 'welcome/index'
  
    resources :posts do
    resources :comments do
    collection do
      post :confirm
    end
    end
  end
  
  resources :comments, only: [:create, :destroy]

  resources :favorites, only: [:create, :destroy]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

 root 'welcome#index'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, :optional => true
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  has_many :comments, dependent: :destroy
  has_many :comment_users, through: :comments, source: :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @favorite = current_user.favorites.find_by(post_id: @post.id)
    @comment = current_user.comments.find_by(post_id: @post.id)
    @posts = current_user.posts
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        PostMailer.post_mail(current_user.email).deliver
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
     @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
     @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :title)
    end
    
    def require_login
     unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_session_path 
     end
    end
  
   def correct_user
     redirect_to(new_user_path) unless @post.user == current_user
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<ul class="row col-sm-12">
  <div class="field" style="margin-top:2%">
     
     <li class="col-sm-2"><%= form.label :title %></li>
     <li class="col-sm-10"><%= form.text_field :title %></li>
 
     <li class="col-sm-2"><%= form.label :image %></li>
     <li class="col-sm-4"><%= form.file_field :image, id: :post_image %></li>
     <li class="col-sm-6"><%= form.hidden_field :image_cache %></li>
  
  </div>

  <div class="actions" style="margin-top:3%">
    <li class="col-sm-10"style="margin-left:50%"><%= form.submit 'Save', data: { confirm: 'Are you sure you want to post this?' } %></li>
  </div>
</ul>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container" style="margin:2% 2% 5% 2%">
    <div id="home">
      <div class="row ">
           <% @posts.each do |post| %>
           <div class="list col-sm-4 ">
              <p>
                <%= image_tag(post.user.image_url, :class => "user") %>
                <%= post.user.name %> 
              </p>
              <p><%= post.title %></p>
              <p><%= link_to image_tag(post.image.url, :class => "imgsize"), post %></p>
             <% if post.user == current_user %>
               <button type="button" class="btn btn-primary"><%= link_to 'Edit', edit_post_path(post) %></button>
               <button type="button" class="btn btn-danger"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></button>
             <% end %>
             </div>
           <% end %>
     </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class="container" style="margin:5% 0 20% 0">
  <div class="row">
    <div class="col-sm-6 text-left" style="margin-left:40%"> 
<h1>Create New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container" style="margin:30px 1px 5% 40% ">
  <div class="row">
    <div class="col-sm-6 text-left" > 
    <p>
      <%= image_tag(@post.user.image_url, :class => "user") %>
      <%= @post.user.name %>
    </p>
     <p>
      <%= @post.title %>
     </p>
     <p>
      <%= image_tag @post.image_url, :class => "imgsize" %>
     </p>
       <p>
        <% if @favorite.present? %>
          <button type="button" class="btn btn-danger"><%= link_to 'Unlike', favorite_path(post_id: @post.id), method: :delete %></button>
        <% else %>
          <button type="button" , class="btn btn-success"><%= link_to 'Like', favorites_path(post_id: @post.id), method: :post %></button>
        <% end %>
        <% if @post.user == current_user %>
          <button type="button" class="btn btn-primary"><%= link_to 'Edit', edit_post_path(@post) %></button>
         <% end %>
       </p>
       <div class="comment">
       <%= render @post.comments %>
       </div>
     <%= render 'comments/form' %>
    </div>
  </div>
</div>