config/routes.rb
Rails.application.routes.draw do
   get 'favorites/new'

  get 'sessions/new'

  get 'welcome/index'
  
    resources :posts do
    resources :comments do
    collection do
      post :confirm
    end
    end
  end
  
  resources :comments, only: [:create, :destroy]

  resources :favorites, only: [:create, :destroy]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
 
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

 root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagramclone</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<div class="container-fluid">
  <% if logged_in? %> 
<header class="header">
<nav class="row navbar navbar-expand-lg">
 <div class="col-sm-1 navbar-header ">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="sr-only"><%= link_to 'Home', controller: 'welcome' %></span>
    <span class="navbar-toggler-icon"></span>
  </button>
 </div>
 
  <div class="col-sm-2 collapse navbar-collapse text-left">
    <a class="nav-link" href="#"><i class="fa fa-instagram" aria-hidden="true" style="font-size:30px;color:white;">Instagram</i></a>
  </div>
  <div class="col-sm-2 collapse navbar-collapse text-right">
    <form class="form-inline">
      <input class="form-control input-sm " type="search" placeholder="Search" aria-label="Search" size="15">
      <button class="btn btn-outline-success " type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
    </form>
  </div>
  <div class="col-sm-9 collapse navbar-collapse text-right">
    <ul class="row">
    <% @user ||= current_user %>
    
      <li><a class="col-sm-1 nav-link" href="#"><%= link_to "Home", root_path, class:'menu' %></a></li>
      <li><a class="col-sm-1 nav-link" href="#"><%= link_to "Profile", user_path(current_user.id), class:'menu' %></a></li>
      <li><a class="col-sm-2 nav-link" href="#"><%= link_to "All Posts", posts_path, class:'menu' %></a></li>
      <li><a class="col-sm-2 nav-link" href="#"><%= link_to "New Post", new_post_path, class:'menu' %></a></li>
      <li><a class="col-sm-1 nav-link" href="#"><%= link_to "Login", new_session_path, class:'menu' %></a></li>
      <li><a class="col-sm-1 nav-link" href="#"><%= link_to "Logout", session_path(current_user.id), method: :delete, class:'menu' %></a></li>
      <li><a class="col-sm-1 nav-link" href="#"><%= link_to image_tag @user.image_url, :class => "profilelogo" %><%= link_to "", user_path(current_user.id) %></a></li>
    
    <% end %>
    </ul>
    </div>
 </nav>
</header>
   <div class="text-center" >
     <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
     <% end %>
    </div>
    <%= yield %>
    <footer>
  <nav class="row">
    <div class="col-md-6 text-center">
      <p>TwitterClone Application</p>
      <p>© 2018 Copyright MAGEZA Adolphe.</p>
    </div>
    <div class="col-md-6 text-center">
        <a class="col-sm-1 nav-link" href="#"><%= link_to "Home", root_path, class:'menu' %></a>
        <a class="col-1" href="#"><%= link_to 'About Us', new_post_path, class:'menu' %></a>
        <a class="col-1" href="#"><%= link_to 'Gallery', new_post_path, class:'menu' %></a>
        <a class="col-1" href="#"><%= link_to 'Contact Us', new_post_path, class:'menu' %></a>
      <!--</li>-->
      <!--<h6>Follow Us on:</h6>-->
      <!--<a class="col-1" href="https://web.facebook.com/adolphe.mageza"><i class="fa fa-facebook-square" aria-hidden="true" style="font-size:40px;color:white;"></i></a>-->
      <!--<a class="col-1" href="https://twitter.com/Admageza"><i class="fa fa-twitter-square" aria-hidden="true" style="font-size:40px;color:white;"></i></a>-->
      <!--<a class="col-1" href="https://secure.skype.com/portal/overview?intsrc=client-_-windows-_-7.40.0.103-_-menu.account"><i class="fa fa-skype" aria-hidden="true" style="font-size:40px;color:white;"></i></a>-->
      <!--<a class="col-1" href="https://www.instagram.com/admageza/?hl=en"><i class="fa fa-instagram" aria-hidden="true" style="font-size:40px;color:white;"></i></a>-->
      <!--<a class="col-1" href="https://www.linkedin.com/in/adolphe-mageza-8a425234/"><i class="fa fa-linkedin-square" aria-hidden="true" style="font-size:40px;color:white;"></i></a>-->
    </div>
    </nav>
  </footer>
   </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="/javascript/script.js"></script>
   
  <script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {
    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
  
  $(window).scroll(function() {
    $(".slideanim").each(function(){
      var pos = $(this).offset().top;

      var winTop = $(window).scrollTop();
        if (pos < winTop + 600) {
          $(this).addClass("slide");
        }
    });
  });
})
</script>
</body>
</html>